### ISSUE TITLE
Crash when running in Visual Studio Code

### ISSUE THREAD

**Issue by rotu** [deno-library/progress#20]
When running under vscode debugger, this package is crashing on the first call to `progress.render` with the error "Error: Operation not supported on socket".

This only seems to happen when running the code via VSCode configuration, not when calling Deno with the builtin terminal.

```
/Users/dan/.deno/bin/deno run --inspect-wait --allow-all ./main.ts

Debugger listening on ws://127.0.0.1:9229/ws/82acfbe9-5635-4e48-8400-7f3ac696c663
Visit chrome://inspect to connect to the debugger.
Deno is waiting for debugger to connect.
Debugger session started.
Debugger session ended
error: Uncaught (in promise) Error: Operation not supported on socket (os error 102)
    return Deno.consoleSize().columns;
                ^
    at Object.consoleSize (internal:runtime/js/40_tty.js:14:9)
    at ProgressBar.get ttyColumns (https://deno.land/x/progress@v1.3.6/mod.ts:237:17)
    at ProgressBar.render (https://deno.land/x/progress@v1.3.6/mod.ts:157:12)
    at file:///path/to/main.ts:79:12
Process exited with code 1
```

My code looks something like this:

```typescript
import ProgressBar from "https://deno.land/x/progress@v1.3.6/mod.ts"
const progress = new ProgressBar()
progress.render(0)
```

and my launch json like this;
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "request": "launch",
      "name": "Launch Program",
      "type": "node",
      "program": "${workspaceFolder}/main.ts",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "${env:HOME}/.deno/bin/deno",
      "runtimeArgs": [
        "run",
        "--inspect-wait",
        "--allow-all"
      ],
      "attachSimplePort": 9229
    },
  ]
}
```

**Comment by fuxingZhang** [comment]
Landed in [v1.3.7](https://github.com/deno-library/progress/releases/tag/v1.3.7)
